version: '3'

networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: postgres:16.2-alpine3.19
    networks:
      - app-tier
    restart: always
    env_file:
      - ./.env
    ports:
      - 5439:5439
  
  app:
    depends_on:
      - postgres
    build: .
    networks:
      - app-tier
    restart: always
    env_file:
      - ./.env
    ports:
      - 8090:8090